OrdererOrgs:
  - Name: Orderer
    Domain: iot.net
    Specs:
      - Hostname: orderer
PeerOrgs:
  - Name: Org1
    Domain: org1.iot.net
    Template:
      Count: 2
    Users:
      Count: 2
  - Name: Org2
    Domain: org2.iot.net
    Template:
      Count: 2
    Users:
      Count: 2
  # - Name: Org3
  #   Domain: org3.iot.net
  #   Template:
  #     Count: 1
  #   Users:
  #     Count: 1