# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  iotn:
services:
  ca0:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org1
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.iot.net-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/59563856a489aeb63a68f1ae48c5b731e238a684943f997b49dc4cb3148a4d26_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.iot.net-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/59563856a489aeb63a68f1ae48c5b731e238a684943f997b49dc4cb3148a4d26_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org1.iot.net/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg1
    networks:
      - iotn

  ca1:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org2
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.iot.net-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/86f0b549eddfca10e06995a738f6d9cf91966f61edf99df9de1d4c3a9b5eddcc_sk
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org2.iot.net-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/86f0b549eddfca10e06995a738f6d9cf91966f61edf99df9de1d4c3a9b5eddcc_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org2.iot.net/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg2
    networks:
      - iotn