# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  byfn:
services:
  ca0:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org1
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.iot.net-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/f0f875f4802df878d77458336f47f2366ea6ceb4e0c27810fc44529155bf3679_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.iot.net-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/f0f875f4802df878d77458336f47f2366ea6ceb4e0c27810fc44529155bf3679_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org1.iot.net/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg1
    networks:
      - byfn

  ca1:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org2
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.iot.net-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/b64c739c52823d8ff9a533ce67ad53a1a88efdc2968716651b8d5f576ef31d6f_sk
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org2.iot.net-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/b64c739c52823d8ff9a533ce67ad53a1a88efdc2968716651b8d5f576ef31d6f_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org2.iot.net/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg2
    networks:
      - byfn