# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  byfn:
services:
  ca0:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org1
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.iot.net-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/79594fad2fc86159c513a531e98b8cb4652fb1cb6b0c47373ab4e46edf25f0c2_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.iot.net-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/79594fad2fc86159c513a531e98b8cb4652fb1cb6b0c47373ab4e46edf25f0c2_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org1.iot.net/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg1
    networks:
      - byfn

  ca1:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org2
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.iot.net-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/361c4a8689359a42079cf89a29033d3ff8883c3caefb12b6ec60c397a8f54b46_sk
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org2.iot.net-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/361c4a8689359a42079cf89a29033d3ff8883c3caefb12b6ec60c397a8f54b46_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org2.iot.net/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg2
    networks:
      - byfn